### ISSUE TITLE
(Suggestion) New texture?

### ISSUE THREAD

**Issue by Rad586** [TrueHorse/Enchantment-Preservation#5]
[item.zip](https://github.com/TrueHorse/Enchantment-Preservation/files/10020276/item.zip)
I redrew the textures of enchantment stones, use it freely if you like!<3

**Comment by TrueHorse** [comment]
Thank you very much for sharing. 🙂 I think they look very cool and from an artistic perspective definitely better than mine. Because of that and because I appreciate you sharing them I want to add them to the mod. But I am torn, because I am not sure if I like them in the context of the mod. With mine I can imagine more easily how you would attache them to a tool... I don't know. For now I will add a link to here to the mod page and think about it again later. Either way thank you again.

**Comment by Rad586** [comment]
What about adding a build-in resourcepack?

**Comment by TrueHorse** [comment]
I didn't know you could do that. 😅

**Comment by Rad586** [comment]
> I didn't know you could do that. 😅

[resourcepack.zip](https://github.com/TrueHorse/Enchantment-Preservation/files/10049464/resourcepack.zip)
